spring:
  application:
    name: eimp-backend

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/eimp}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

server:
  port: ${SERVER_PORT:8081}

logging:
  level:
    org.springframework.security: INFO

app:
  jwt:
    secret: ${JWT_SECRET}