package com.rejili.eimp.service;

import com.rejili.eimp.entity.MonitoringMetric;
import com.rejili.eimp.entity.VirtualMachine;
import com.rejili.eimp.repository.MonitoringMetricRepository;
import com.rejili.eimp.repository.VirtualMachineRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;

@Service
@RequiredArgsConstructor
public class MonitoringService {

    private final MonitoringMetricRepository monitoringMetricRepository;

    private final VirtualMachineRepository virtualMachineRepository;

    private final AlertService alertService;

    public List<MonitoringMetric> getMetricsByVirtualMachine(
            Long virtualMachineId) {

        getVirtualMachine(virtualMachineId);

        return monitoringMetricRepository
                .findByVirtualMachineIdOrderByRecordedAtDesc(
                        virtualMachineId
                );
    }

    public List<MonitoringMetric> getMetricsByVirtualMachineAndPeriod(
            Long virtualMachineId,
            LocalDateTime start,
            LocalDateTime end) {

        getVirtualMachine(virtualMachineId);

        if (start.isAfter(end)) {
            throw new IllegalArgumentException(
                    "Start date must be before end date"
            );
        }

        return monitoringMetricRepository
                .findByVirtualMachineIdAndRecordedAtBetweenOrderByRecordedAtDesc(
                        virtualMachineId,
                        start,
                        end
                );
    }

    public MonitoringMetric createMetric(
            Long virtualMachineId,
            MonitoringMetric metric) {

        VirtualMachine virtualMachine =
                getVirtualMachine(virtualMachineId);

        validateMetric(metric);

        /*
         * The ID is generated by PostgreSQL/JPA.
         * Prevent clients from forcing an existing ID.
         */
        metric.setId(null);

        /*
         * Associate the metric with the requested VM.
         */
        metric.setVirtualMachine(virtualMachine);

        /*
         * If no timestamp was provided by the client,
         * use the current server time.
         */
        if (metric.getRecordedAt() == null) {
            metric.setRecordedAt(LocalDateTime.now());
        }

        /*
         * Save monitoring metric first.
         */
        MonitoringMetric savedMetric =
                monitoringMetricRepository.save(metric);

        /*
         * Evaluate CPU/RAM/Disk thresholds
         * and automatically create alerts if required.
         */
        alertService.evaluateMetric(savedMetric);

        return savedMetric;
    }

    private VirtualMachine getVirtualMachine(Long id) {

        return virtualMachineRepository.findById(id)
                .orElseThrow(() ->
                        new RuntimeException(
                                "Virtual machine not found with id: " + id
                        )
                );
    }

    private void validateMetric(MonitoringMetric metric) {

        validatePercentage(
                metric.getCpuUsagePercent(),
                "CPU usage"
        );

        validatePercentage(
                metric.getRamUsagePercent(),
                "RAM usage"
        );

        validatePercentage(
                metric.getDiskUsagePercent(),
                "Disk usage"
        );

        if (metric.getNetworkInMbps() != null &&
                metric.getNetworkInMbps() < 0) {

            throw new IllegalArgumentException(
                    "Network input cannot be negative"
            );
        }

        if (metric.getNetworkOutMbps() != null &&
                metric.getNetworkOutMbps() < 0) {

            throw new IllegalArgumentException(
                    "Network output cannot be negative"
            );
        }
    }

    private void validatePercentage(
            Double value,
            String fieldName) {

        if (value == null || value < 0 || value > 100) {

            throw new IllegalArgumentException(
                    fieldName + " must be between 0 and 100"
            );
        }
    }
}